### ISSUE TITLE
Passing in a command using '+' gives me E481: No range allowed error

### ISSUE THREAD

**Issue by beelzebielsk** [mhinz/neovim-remote#115]
I'm running a command straight from the help description

    nvr --remote-tab-wait +'set bufhidden=delete' file

With `file` changed to something that exists on my computer. My nvr version is `2.2.0`, and my nvim version is `0.3.8`.  I get the error E481: No range allowed. The exact stacktrace I get back from nvr is:

EDIT: My python version is `3.7.4`

~~~
Traceback (most recent call last):
  File "/usr/bin/nvr", line 11, in <module>
    load_entry_point('neovim-remote==2.2.0', 'console_scripts', 'nvr')()
  File "/usr/lib/python3.7/site-packages/nvr/nvr.py", line 434, in main
    nvr.execute(options.remote_tab_wait + arguments, 'tabedit', wait=True)
  File "/usr/lib/python3.7/site-packages/nvr/nvr.py", line 149, in execute
    self.server.command(cmd if cmd else '$')
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(set):E481: No range allowed'
~~~

And the command isn't run.

**Comment by jan0sch** [comment]
I can confirm this bug. Recently I updated my neovim-remote (after a _long_ time) and instantly got this error.

* neovim : 0.3.8
* neovim-remote : 2.2.0
* python : 3.6.9

The file is openend in neovim but the command is not run as stated above.

**Comment by mhinz** [comment]
Yes, the `+` syntax was broken. Should work again with the latest neovim-remote.
