### ISSUE TITLE
nvr hangs on windows

### ISSUE THREAD

**Issue by jmlucjav** [mhinz/neovim-remote#163]
Hi,

I am setting up a new laptop and nvr is not working for me. I have (what I think is) the same neovim/python/neovim-remote configuration from my destkop (most config files are synchronized etc) and I don't know what else I could try.

Env:

- win10 20H2
- python 3.8.8 (same behaviour with 3.9.2 which I though was the culprit, but downgrading to 3.8 makes no difference)

Symptoms are:

- it does not matter if neovim is running alread or not
- running just nvr:

```
c:\temp>nvr

c:\temp>
```

- running it to connect to existing neovim, it hangs, if I Control-C after a while, I get exception below

```
c:\temp>nvr --nostart filesql.sql
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\nvr.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\nvr\nvr.py", line 506, in main
    nvr.execute(arguments, 'edit', silent=True)
  File "c:\python38\lib\site-packages\nvr\nvr.py", line 138, in execute
    self.fnameescaped_command(cmd, fname)
  File "c:\python38\lib\site-packages\nvr\nvr.py", line 97, in fnameescaped_command
    path = self.server.funcs.fnameescape(path)
  File "c:\python38\lib\site-packages\pynvim\api\nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "c:\python38\lib\site-packages\pynvim\api\nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "c:\python38\lib\site-packages\pynvim\msgpack_rpc\session.py", line 95, in request
    v = self._blocking_request(method, args)
  File "c:\python38\lib\site-packages\pynvim\msgpack_rpc\session.py", line 174, in _blocking_request
    self._async_session.run(self._enqueue_request,
  File "c:\python38\lib\site-packages\pynvim\msgpack_rpc\async_session.py", line 66, in run
    self._msgpack_stream.run(self._on_message)
  File "c:\python38\lib\site-packages\pynvim\msgpack_rpc\msgpack_stream.py", line 43, in run
    self.loop.run(self._on_data)
  File "c:\python38\lib\site-packages\pynvim\msgpack_rpc\event_loop\base.py", line 144, in run
    self._run()
  File "c:\python38\lib\site-packages\pynvim\msgpack_rpc\event_loop\asyncio.py", line 136, in _run
    self._loop.run_forever()
  File "c:\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\python38\lib\asyncio\base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "c:\python38\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "c:\python38\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016AC1AA0AF0>
Traceback (most recent call last):
  File "c:\python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "c:\python38\lib\asyncio\proactor_events.py", line 108, in close
  File "c:\python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "c:\python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
^C
c:\temp>
```

Does anybody have a clue? this is driving me mad....

thanks!

**Comment by jmlucjav** [comment]
ok, fixed it with 

```
:let g:loaded_python3_provider = 0
```

I am not sure what was the issue, checkhealth was reporting weird issues with python (that did not make sense to me)
