### ISSUE TITLE
Add parameter to nvr to add 'set bufhidden=delete'

### ISSUE THREAD

**Issue by HarmtH** [mhinz/neovim-remote#26]
I'm using ```nvr --remote-tab-wait``` as ```$EDITOR``` a lot from ```:term``` and I always accidentally quit with ```:wq```, which doesn't notify the calling term. Having a parameter to ```nvr``` to add ```set bufhidden=delete``` to the buffer would be a really nice addition.

**Comment by mhinz** [comment]
That's a user workflow issue really. :-)

But you can execute any command after opening buffers using `+`. I suggest aliasing:

```
nvr --remote-tab-wait +'set bufhidden=delete'
```

**Comment by mhinz** [comment]
Done! Thanks for pointing this out.

**Comment by rperryng** [comment]
I'm having a hard time passing vim options to nvr.  In my `.zshrc` I have the following:

```sh
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
  export VISUAL="nvr -cc split --remote-wait +'setlocal bufhidden=wipe'"
  alias nv="nvr"
else
  export VISUAL=nvim
  alias nv="nvim"
fi
export EDITOR="$VISUAL"
```

Say I have entered a neovim terminal, and I have the text `Hello World` on my prompt.  If I hit `<C-x><C-e>`, I end up with 2 extra buffers

1. A temporary buffer containing the text "Hello World".  When i navigate to it I am informed it's no longer available
2. An empty third buffer named `bufhidden=wipe'`

The buffer with terminal spits out

```
➜ hello worldTraceback (most recent call last):
  File "/Users/rperrynguyen/.pyenv/versions/3.4.4/bin/nvr", line 11, in <module>
    sys.exit(main())
  File "/Users/rperrynguyen/.pyenv/versions/3.4.4/lib/python3.4/site-packages/nvr/nvr.py", line 368, in main
    nfiles = nvim.execute(options.remote_wait + arguments, 'edit', wait=True)
  File "/Users/rperrynguyen/.pyenv/versions/3.4.4/lib/python3.4/site-packages/nvr/nvr.py", line 137, in execute
    self.server.command(cmd if cmd else '$')
  File "/Users/rperrynguyen/.pyenv/versions/3.4.4/lib/python3.4/site-packages/neovim/api/nvim.py", line 218, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/rperrynguyen/.pyenv/versions/3.4.4/lib/python3.4/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/rperrynguyen/.pyenv/versions/3.4.4/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
```

If I remove the `+'setlocal bufhidden=wipe'` the expected behaviour occurs

**Comment by mhinz** [comment]
@rperryng Thanks for reporting this. I found the problem and will upload a fix tomorrow.

**Comment by mhinz** [comment]
@rperryng Actually, it's a zsh issue. I posted a bug report: http://www.zsh.org/mla/workers/2017/msg01545.html

**Comment by rperryng** [comment]
@mhinz Thanks so much for keeping me informed.  Hopefully this gets resolved soon!

**Comment by mhinz** [comment]
@rperryng 

Fixed! https://github.com/zsh-users/zsh/commit/96845524a66aecfd4fa01f1b23f80bbf753f1130

The last zsh release was 7 weeks ago, so the next one is probably not far away.

**Comment by 3v0k4** [comment]
Not sure if this is related but I have a similar problem as @rperryng's.

I'm on zsh
```
echo $ZSH_VERSION
# 5.7.1
zsh --version
# zsh 5.7.1 (x86_64-apple-darwin16.7.0)
```
which should be the one with the fix.

Neovim
```
nvim --version
# NVIM v0.3.4
```

In my .zshrc
```
export VISUAL="nvr -cc split --remote-wait +'setlocal bufhidden=wipe'"
```

When in terminal mode in nvim I do `<C-x><C-e>` I get
```
  File "/Users/rysiek/Library/Python/3.7/bin/nvr", line 11, in <module>
    sys.exit(main())
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/nvr/nvr.py", line 421, in main
    nvr.execute(options.remote_wait + arguments, 'edit', wait=True)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/nvr/nvr.py", line 145, in execute
    self.server.command(cmd if cmd else '$')
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim:E20: Mark not set'
```

Without  ` +'setlocal bufhidden=wipe` in my .zscrc
```
export VISUAL="nvr -cc split --remote-wait"
```
the split opens w/o errors.

Let me know if I can provide more info on this in case anybody's willing to help!
