### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mmynsted** [mhinz/neovim-remote#33]
## platform
`Darwin Kernel Version 15.6.0`
`OS X El Capitan Version 10.11.6`

## install steps
`sudo pip-3.5 install neovim-remote`

## issue
`nvr`

`-bash: nvr: command not found`

**Comment by mhinz** [comment]
You installed it as root and tried to run it as user? Don't do that. :)

If you installed Python 3 via `brew`, the `sudo` shouldn't be needed. Then it will install to `/usr/local/bin` instead.

**Comment by mmynsted** [comment]
How about this?

```bash 
0:42 $ pip install neovim-remote
Collecting neovim-remote
  Downloading neovim-remote-1.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h_/45t2nwln0q37lsb_g6pbv5sh0000gn/T/pip-build-zVF5R2/neovim-remote/setup.py", line 6, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h_/45t2nwln0q37lsb_g6pbv5sh0000gn/T/pip-build-zVF5R2/neovim-remote/
```

**Comment by mmynsted** [comment]
Oh, also I use macports not homebrew.  (macports is not always as up-to-date as homebrew but I have had better over-all results with macports)

**Comment by mmynsted** [comment]
```bash
11:01 $ pip-3.5 install neovim-remote

Collecting neovim-remote
  Using cached neovim_remote-1.4.4-py3-none-any.whl
Requirement already satisfied: neovim in /Users/mmynsted/Library/Python/3.5/lib/python/site-packages (from neovim-remote)
Requirement already satisfied: msgpack-python>=0.4.0 in /Users/mmynsted/Library/Python/3.5/lib/python/site-packages (from neovim->neovim-remote)
Requirement already satisfied: greenlet in /Users/mmynsted/Library/Python/3.5/lib/python/site-packages (from neovim->neovim-remote)
Installing collected packages: neovim-remote
Exception:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neovim_remote-1.4.4.dist-info'
```

**Comment by mhinz** [comment]
Does `pip3.5 install --user neovim-remote` make any difference?

Apparently the dependencies are already installed in `/Users/mmynsted/Library/Python/3.5`.

**Comment by mmynsted** [comment]
:-)  Yes.  That worked!  Thank you.

**Comment by mhinz** [comment]
Okay, I added the `--user` part to the README. Thanks for bringing this up!
