### ISSUE TITLE
Server does not seem to be created

### ISSUE THREAD

**Issue by devgg** [mhinz/neovim-remote#56]
I am on OSX and zsh. When I run `NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim file.txt` and then run `nvr --serverlist` in another shell I get no output.

When I then run `nvr --remote-send 'iabc<cr><esc>'`  a new instance of nvim opens with the following output:

    Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=False debug=False>>
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 512, in __del__
        self.close()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/unix_events.py", line 63, in close
        super().close()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 110, in close
        self._close_self_pipe()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 120, in _close_self_pipe
        self._remove_reader(self._ssock.fileno())
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 279, in _remove_reader
        key = self._selector.get_key(fd)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 189, in get_key
        return mapping[fileobj]
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 70, in __getitem__
        fd = self._selector._fileobj_lookup(fileobj)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
        return _fileobj_to_fd(fileobj)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 41, in _fileobj_to_fd
        raise ValueError("Invalid file descriptor: {}".format(fd))
    ValueError: Invalid file descriptor: -1

I have no idea what is going on 😢 .

**Comment by davidosomething** [comment]
On OSX I use a user owned directory (e.g. `mkdir -p ~/.local/tmp && ~/.local/tmp` `export NVIM_LISTEN_ADDRESS=~/.local/tmp/nvimsocket`)

Reasoning:

- My python is installed via pyenv, so when I run python it runs as myself (unless I use su/sudo)
- neovim-remote is installed via pip in the pyenv, so the provided nvr binary runs as myself (unless I use su/sudo)
- On OSX, `/tmp` is owned and only writable by `root:wheel`
- nvr, running as myself, is nor running as root or in wheel, so it will fail to create the socket

There's other reasons not to use a shared global `/tmp` also (e.g. multiuser machine).

**Comment by devgg** [comment]
Cool that worked!

Thanks a lot 👍

**Comment by mhinz** [comment]
There shouldn't be any problem with using `/tmp`, since its permissions are set to 1777, so every user can read, create and delete only files that belong to her. So, if the user's umask is 077, no one can read your files.

Are there any reliable steps to reproduce this?
