### ISSUE TITLE
msgpack-python not found, but installed

### ISSUE THREAD

**Issue by R3load** [mhinz/neovim-remote#73]
```
Traceback (most recent call last):
  File "/usr/bin/nvr", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python>=0.4.0' distribution was not found and is required by neovim
```

```
~/local/build/aur/neovim-remote
❯ /usr/bin/nvim --version                          
NVIM v0.2.2-48-gf19e5d653
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/rogue/aur/neovim-git/src/neovim-git/build/config -I/home/rogue/aur/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/rogue/aur/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/rogue/aur/neovim-git/src/neovim-git/build/include
Compiled by rogue@shadow

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

~/local/build/aur/neovim-remote
❯ pacman -Q neovim-git neovim-remote python-msgpack
neovim-git 0.2.1.r48.gf19e5d653-1
neovim-remote 1.9.0-1
python-msgpack 0.5.0-1
```

After a system upgrade `nvr` stopped working on Arch Linux, but `nvim` works fine.

**Comment by mhinz** [comment]
Well, the message says:

```
The 'msgpack-python>=0.4.0' distribution was not found and is required by neovim
```

This is an issue with your Python environment. Since you use your package manager instead of `pip3`, and since I never used Arch, I can't give you any good tips on what's wrong.

Your best bet is to ask the maintainer of the package: https://aur.archlinux.org/packages/neovim-remote

Thanks!

**Comment by mhinz** [comment]
FWIW, the issue is mentioned here: https://pypi.python.org/pypi/msgpack/0.5.1

```
When upgrading from msgpack-0.4 or earlier, don’t do pip install -U msgpack-python. Do pip uninstall msgpack-python; pip install msgpack instead.
```

So, the package used to be called `msgpack-python`, which is a transition package for `msgpack` now. Somewhere along these lines something broke in the Arch package, I guess.
