### ISSUE TITLE
Syntax error with python 3.7

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#79]
I'm trying out the 3.7 beta, and I get the following error when I just type `nvr`:

```
Traceback (most recent call last):
  File "/Users/alokbeniwal/Library/Python/3.7/bin/nvr", line 7, in <module>
    from nvr.nvr import main
  File "/Users/alokbeniwal/Library/Python/3.7/lib/python/site-packages/nvr/__init__.py", line 1, in
<module>
    from .nvr import main
  File "/Users/alokbeniwal/Library/Python/3.7/lib/python/site-packages/nvr/nvr.py", line 26, in <mod
ule>
    import neovim
  File "/Users/alokbeniwal/Library/Python/3.7/lib/python/site-packages/neovim/__init__.py", line 9,
in <module>
    from .api import Nvim
  File "/Users/alokbeniwal/Library/Python/3.7/lib/python/site-packages/neovim/api/__init__.py", line
 7, in <module>
    from .buffer import Buffer
  File "/Users/alokbeniwal/Library/Python/3.7/lib/python/site-packages/neovim/api/buffer.py", line 1
01
    col_end=-1, src_id=-1, async=None):
                               ^
SyntaxError: invalid syntax
```

**Comment by mhinz** [comment]
That's an issue in the python-client. See: https://github.com/neovim/python-client/pull/274

Unfortunately it doesn't seem to be possible to add version constraints to setup.py itself, so I'll make nvr drop out with a meaningful message.
