### ISSUE TITLE
Error: DistributionNotFound: neovim>=0.2.3 

### ISSUE THREAD

**Issue by doronbehar** [mhinz/neovim-remote#90]
Does anyone else has this error:
```
Traceback (most recent call last):
  File "/usr/bin/nvr", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'neovim>=0.2.3' distribution was not found and is required by neovim-remote
```
?

**Comment by mhinz** [comment]
Your `/usr/bin/nvr` seems to be out-of-date. The reference to `neovim >= 0.2.3` was removed when we switched to pynvim: https://github.com/mhinz/neovim-remote/commit/7c50a1ef325205af40ab26667e9c41ab87364b20#diff-2eeaed663bd0d25b7e608891384b7298L17

Make sure you're using `v2.1.1`.
